import OpenInNewRoundedIcon from '@mui/icons-material/OpenInNewRounded';
import SearchRoundedIcon from '@mui/icons-material/SearchRounded';
import {
  IconButton,
  InputAdornment,
  MenuItem,
  Paper,
  Stack,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  TextField,
  Tooltip,
  Typography,
} from '@mui/material';
import { useQuery } from '@tanstack/react-query';
import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';

import { AsyncState } from '@/components/AsyncState';
import { PageHeader } from '@/components/PageHeader';
import { StatusBadge } from '@/components/StatusBadge';
import { getApi, toErrorMessage } from '@/lib/api';
import { formatDateTime } from '@/lib/date';
import { formatSignedMoney } from '@/lib/money';
import { transactionsSchema } from '@/lib/schemas';

export function PaymentsPage() {
  const [query, setQuery] = useState('');
  const [status, setStatus] = useState('ALL');
  const transactions = useQuery({
    queryKey: ['customer', 'transactions'],
    queryFn: () => getApi('/api/v1/me/transactions?limit=100', transactionsSchema),
  });

  const filtered = useMemo(() => {
    const normalizedQuery = query.trim().toLocaleLowerCase();
    return (transactions.data ?? []).filter((transaction) => {
      const matchesQuery =
        normalizedQuery.length === 0 ||
        transaction.description.toLocaleLowerCase().includes(normalizedQuery) ||
        transaction.counterparty.toLocaleLowerCase().includes(normalizedQuery) ||
        transaction.id.toLocaleLowerCase().includes(normalizedQuery);
      return matchesQuery && (status === 'ALL' || transaction.status === status);
    });
  }, [query, status, transactions.data]);

  return (
    <>
      <PageHeader
        eyebrow="Customer banking"
        title="Payments and transfers"
        description="Inspect internal, interbank, phone-alias, QR, card, and ATM activity generated by the simulator."
      />
      <Stack direction={{ xs: 'column', sm: 'row' }} gap={1.5} sx={{ mb: 2 }}>
        <TextField
          label="Search transactions"
          value={query}
          onChange={(event) => setQuery(event.target.value)}
          fullWidth
          slotProps={{
            input: {
              startAdornment: (
                <InputAdornment position="start">
                  <SearchRoundedIcon />
                </InputAdornment>
              ),
            },
          }}
        />
        <TextField select label="Status" value={status} onChange={(event) => setStatus(event.target.value)} sx={{ minWidth: 190 }}>
          {['ALL', 'PENDING', 'PROCESSING', 'COMPLETED', 'REJECTED', 'FAILED'].map((item) => (
            <MenuItem key={item} value={item}>
              {item.replaceAll('_', ' ')}
            </MenuItem>
          ))}
        </TextField>
      </Stack>
      <AsyncState
        loading={transactions.isPending}
        label="Loading payments"
        error={transactions.isError ? toErrorMessage(transactions.error) : null}
        onRetry={() => void transactions.refetch()}
        empty={transactions.data !== undefined && filtered.length === 0}
        emptyTitle="No matching transactions"
        emptyBody="Adjust the search or status filter, or create a new simulated transfer."
      >
        <TableContainer component={Paper} variant="outlined">
          <Table aria-label="Payments and transfers">
            <TableHead>
              <TableRow>
                <TableCell>Date</TableCell>
                <TableCell>Description</TableCell>
                <TableCell>Rail</TableCell>
                <TableCell>Status</TableCell>
                <TableCell align="right">Amount</TableCell>
                <TableCell padding="checkbox"><span className="sr-only">Open</span></TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {filtered.map((transaction) => (
                <TableRow key={transaction.id} hover>
                  <TableCell>{formatDateTime(transaction.createdAt)}</TableCell>
                  <TableCell>
                    <Typography variant="body2" sx={{ fontWeight: 700 }}>{transaction.description}</Typography>
                    <Typography variant="caption" color="text.secondary">{transaction.counterparty}</Typography>
                  </TableCell>
                  <TableCell>{transaction.rail}</TableCell>
                  <TableCell><StatusBadge status={transaction.status} /></TableCell>
                  <TableCell align="right" sx={{ fontVariantNumeric: 'tabular-nums', fontWeight: 700 }}>
                    {formatSignedMoney(
                      transaction.direction === 'DEBIT' ? `-${transaction.amount}` : transaction.amount,
                      transaction.currency,
                    )}
                  </TableCell>
                  <TableCell padding="checkbox">
                    <Tooltip title="Open transaction">
                      <IconButton
                        component={Link}
                        to={`/customer/transactions/${encodeURIComponent(transaction.id)}`}
                        aria-label={`Open transaction ${transaction.id}`}
                      >
                        <OpenInNewRoundedIcon />
                      </IconButton>
                    </Tooltip>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
      </AsyncState>
    </>
  );
}
